# Generated by Django 5.2.8 on 2026-01-19 10:42

from django.db import migrations, models, connection


def rename_tables_if_needed(apps, schema_editor):
    """
    Условное переименование таблиц: переименовывает только если таблицы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен на новые
        table_mappings = {
            'vacancies_parser_habr_career_vacancy': 'vpm_hc_vacancy',
            'vacancies_parser_habr_career_vacancyversion': 'vpm_hc_vacancy_version',
            'vacancies_parser_habr_career_vacancychangehistory': 'vpm_hc_vacancy_change_history',
        }
        
        for old_name, new_name in table_mappings.items():
            # Проверяем, существует ли таблица со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли таблица с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старая таблица существует, а новая - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER TABLE "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Таблица {old_name} переименована в {new_name}")
            elif new_exists:
                print(f"[INFO] Таблица {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Таблица {old_name} не существует, переименование не требуется")


def rename_indexes_if_needed(apps, schema_editor):
    """
    Условное переименование индексов: переименовывает только если индексы
    со старыми именами существуют.
    """
    with connection.cursor() as cursor:
        # Маппинг старых имен индексов на новые (из миграции 0001)
        index_mappings = [
            ('vacancies_p_title_abdde4_idx', 'vpm_hc_vaca_title_abdde4_idx'),
            ('vacancies_p_company_518ca5_idx', 'vpm_hc_vaca_company_518ca5_idx'),
            ('vacancies_p_city_534235_idx', 'vpm_hc_vaca_city_534235_idx'),
            ('vacancies_p_publish_99d469_idx', 'vpm_hc_vaca_publish_99d469_idx'),
            ('vacancies_p_habr_id_6dc4b2_idx', 'vpm_hc_vaca_habr_id_6dc4b2_idx'),
            ('vacancies_p_current_b2673f_idx', 'vpm_hc_vaca_current_b2673f_idx'),
            ('vacancies_p_vacancy_a57fbd_idx', 'vpm_hc_vaca_vacancy_a57fbd_idx'),
            ('vacancies_p_created_6d9b9d_idx', 'vpm_hc_vaca_created_6d9b9d_idx'),
            ('vacancies_p_vacancy_c0880c_idx', 'vpm_hc_vaca_vacancy_c0880c_idx'),
            ('vacancies_p_field_n_a202d4_idx', 'vpm_hc_vaca_field_n_a202d4_idx'),
        ]
        
        for old_name, new_name in index_mappings:
            # Проверяем, существует ли индекс со старым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [old_name])
            
            old_exists = cursor.fetchone()[0]
            
            # Проверяем, существует ли индекс с новым именем
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = %s
                );
            """, [new_name])
            
            new_exists = cursor.fetchone()[0]
            
            # Переименовываем только если старый индекс существует, а новый - нет
            if old_exists and not new_exists:
                cursor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')
                print(f"[INFO] Индекс {old_name} переименован в {new_name}")
            elif new_exists:
                print(f"[INFO] Индекс {new_name} уже существует, переименование не требуется")
            else:
                print(f"[INFO] Индекс {old_name} не существует, переименование не требуется")


def reverse_rename_tables(apps, schema_editor):
    """
    Обратное переименование (для rollback).
    """
    with connection.cursor() as cursor:
        table_mappings = {
            'vpm_hc_vacancy': 'vacancies_parser_habr_career_vacancy',
            'vpm_hc_vacancy_version': 'vacancies_parser_habr_career_vacancyversion',
            'vpm_hc_vacancy_change_history': 'vacancies_parser_habr_career_vacancychangehistory',
        }
        
        for new_name, old_name in table_mappings.items():
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
            """, [new_name])
            
            if cursor.fetchone()[0]:
                cursor.execute(f'ALTER TABLE "{new_name}" RENAME TO "{old_name}";')
                print(f"[INFO] Таблица {new_name} переименована обратно в {old_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_habr_career', '0001_initial'),
    ]

    operations = [
        # Условное переименование таблиц (если они еще не переименованы)
        migrations.RunPython(rename_tables_if_needed, reverse_rename_tables),
        # Обновляем только метаданные моделей (без переименования в БД)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='vacancy',
                    table='vpm_hc_vacancy',
                ),
                migrations.AlterModelTable(
                    name='vacancychangehistory',
                    table='vpm_hc_vacancy_change_history',
                ),
                migrations.AlterModelTable(
                    name='vacancyversion',
                    table='vpm_hc_vacancy_version',
                ),
            ],
        ),
        # Условное переименование индексов (если они еще не переименованы)
        migrations.RunPython(rename_indexes_if_needed, migrations.RunPython.noop),
        # Обновляем метаданные индексов (без переименования в БД)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hc_vaca_title_abdde4_idx',
                    old_name='vacancies_p_title_abdde4_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hc_vaca_company_518ca5_idx',
                    old_name='vacancies_p_company_518ca5_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hc_vaca_city_534235_idx',
                    old_name='vacancies_p_city_534235_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hc_vaca_publish_99d469_idx',
                    old_name='vacancies_p_publish_99d469_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hc_vaca_habr_id_6dc4b2_idx',
                    old_name='vacancies_p_habr_id_6dc4b2_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancy',
                    new_name='vpm_hc_vaca_current_b2673f_idx',
                    old_name='vacancies_p_current_b2673f_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancyversion',
                    new_name='vpm_hc_vaca_vacancy_a57fbd_idx',
                    old_name='vacancies_p_vacancy_a57fbd_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancyversion',
                    new_name='vpm_hc_vaca_created_6d9b9d_idx',
                    old_name='vacancies_p_created_6d9b9d_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_hc_vaca_vacancy_c0880c_idx',
                    old_name='vacancies_p_vacancy_c0880c_idx',
                ),
                migrations.RenameIndex(
                    model_name='vacancychangehistory',
                    new_name='vpm_hc_vaca_field_n_a202d4_idx',
                    old_name='vacancies_p_field_n_a202d4_idx',
                ),
            ],
        ),
    ]
