# Generated by Django 5.2.8 on 2026-01-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_habr_career', '0002_rename_tables_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='vpm_hc_vaca_title_3cd1da_idx',
            old_name='vpm_hc_vaca_title_abdde4_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='vpm_hc_vaca_company_34f3fa_idx',
            old_name='vpm_hc_vaca_company_518ca5_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='vpm_hc_vaca_city_acb191_idx',
            old_name='vpm_hc_vaca_city_534235_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='vpm_hc_vaca_publish_f7ef2f_idx',
            old_name='vpm_hc_vaca_publish_99d469_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='vpm_hc_vaca_habr_id_362fea_idx',
            old_name='vpm_hc_vaca_habr_id_6dc4b2_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='vpm_hc_vaca_current_182810_idx',
            old_name='vpm_hc_vaca_current_b2673f_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancychangehistory',
            new_name='vpm_hc_vaca_vacancy_e2b460_idx',
            old_name='vpm_hc_vaca_vacancy_c0880c_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancychangehistory',
            new_name='vpm_hc_vaca_field_n_48025b_idx',
            old_name='vpm_hc_vaca_field_n_a202d4_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancyversion',
            new_name='vpm_hc_vaca_vacancy_cd0271_idx',
            old_name='vpm_hc_vaca_vacancy_a57fbd_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancyversion',
            new_name='vpm_hc_vaca_created_47bd8c_idx',
            old_name='vpm_hc_vaca_created_6d9b9d_idx',
        ),
    ]
